Style/Documentation:
  Enabled: true

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  ExcludedMethods:
    - configure
    - context
    - define
    - describe
    - draw
    - factory
    - feature
    - guard
    - included
    - it
    - let
    - let!
    - scenario
    - setup
    - shared_context
    - shared_examples
    - shared_examples_for

inherit_from: .rubocop_todo.yml
